-- English localization file for enUS and enGB.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("OUI", "enUS", true)
if not L then return end

-- Menu
L["Action Bars"] = true
	L["Customize your actionbars"] = true
L["Nameplates"] = true
L["Unit Frames"] = true
L["Raid/Party Settings"] = true
L["Data Texts"] = true
L["Chat"] = true
L["Misc"] = true
L["Tooltip"] = true
L["Media"] = true
L["Class Timers"] = true
L["Filters"] = true
L["Profiles"] = true
L["RELOAD_UI"] = "A setting you have changed requires a Reload UI for changes to take effect, when you are done configing hit Accept to APPLY your changes!"

-- General Section
L["General Settings"] = true
	L["OUI_INTRO"] = "Complete UI replacement based off Tukui. Creditz: Tukz, Elv, Dajova, and everyone else in the Tukui Community"
	L["Auto Scale"] = true
		L["GEN_ASCALE"] = "Automatically scale the UI based on your current screen resolution"
	L["Scale"] = true
		L["GEN_SCALE"] = "Manualy adjust the scale of your UI"
	L["Multisample Protection"] = true
		L["GEN_SAMPLE"] = "Force the Blizzard Multisample Option to be set to 1x. WARNING: Turning this off will lead to blurry borders"
	L["Class Color Theme"] = true
		L["Style all frame borders to be your class color, color unitframes to class color"] = true
	L["Font Scale"] = true
		L["Set the font scale for everything in UI. Note: This doesn't effect somethings that have their own seperate options (UnitFrame Font, Datatext Font, ect..)"] = true
	L["Resolution Override"] = true
		L["OVERRIDE_DESC"] = "Set a resolution version to use. By default any screensize > 1440 is considered a High resolution. This effects actionbar/unitframe layouts. If set to None, then it will be automatically determined by your screen size"
			L["Low"] = true
			L["High"] = true
	L["Color Options"] = true
	L["Healthbar Color"] = true
		L["HBAR_DESC"] = "Allows you to select a custom color for health bars"
	L["Healthbar BG Color"] = true
		L["HBARBG_DESC"] = "Allows you to select a custom color for health bars BG"
	L["Transparency"] = true
		L["TRANS_DESC"] = "Adjusts the transparency of transparent windows. (Setting to 1 disables this function)"
	L["Theme"] = true
		L["THEME_DESC"] = "Choose the Look 'N' Feel of the interface."
			L["ClassColor"] = "ClassColor"
			L["Default"] = "Default"
	L["Datatext Height"] = true
		L["Adjust the height of the datatext panels."] = true
		
-- Unit Frames
L["Unit Frames"] = true
	L["Configure Settings for Unit Frames"] = "Configure settings for Unit Frames"
	L["Enable or Disable Unit Frames"] = "Enable or Disable Unit Frames"
	L["Arena Frames"] = true
	L["General Options"] = true
	L["Show Hostility Color"] = true
		L["Enemy target (players) color by hostility, very useful for healer."] = true
	L["Portraits"] = true
		L["Enable displaying character portraits on select frames"] = true
	L["Total HP/MP"] = true
		L["Changes the display of info text on player and target frame with XXXX/Total if enabled."] = true
	L["Show PVP Target Mana"] = true
		L["When enabled will show pvp targets amount of mana."] = true
	L["Smooth Bars"] = true
		L["Enables bars having a smooth look n feel."] = true
	L["Combat Feedback"] = true
		L["Enable combat text on player and target"] = true
	L["Player Aggro"] = true
		L["Enable coloring border red when player has aggro"] = true
	L["Show Percentages"] = true
		L["Enable showing percentages for health/mana outside of unitframes."] = true
	L["Vengeance Bar"] = true
		L["Enable displaying a vengeance bar over bottom middle datatext panel."] = true
	L["Swing bar"] = true
		L["Enable showing your swingbar."] = true
	L["Low Mana Threshold"] = true
		L["When to be warned about low mana"] = true
	L["Debuff Highlighting"] = true
		L["Enable highlighting unitframes when there is a debuff you can dispel"] = true
L["Castbar"] = true
	L["Enable/Disable Castbars"] = true
	L["Castbar Latency"] = true
		L["Show latency on player castbar"] = true
	L["Castbar Icons"] = true
		L["Show icons on castbars"] = true
	L["Width Player Castbar"] = true
	L["Width Target Castbar"] = true
	L["Width Focus Castbar"] = true
	L["Height Player Castbar"] = true
	L["Height Target Castbar"] = true
	L["Height Focus Castbar"] = true
		L["The size of the castbar"] = true
	L["Castbar Color"] = true
	L["Color of the castbar"] = true
	L["Interrupt Color"] = true
	L["Color of the castbar when you can't interrupt the cast"] = true
	L["Castbar Ticks"] = true
		L["Display ticks on castbar when you cast a spell that is channeled, this list may be modified under filters"] = true
	L["Inside UF"] = true
		L["When enabled castbars are inside of your player/target frame. (ONLY WORKS IF LARGE PLAYER CASTBAR IS DISABLED)"] = true
	L["Large Player castbar"] = true
		L["Allows you to use a bigger castbar for your casts"] = true
L["Auras"] = true
	L["Aura Timers"] = true
		L["Enables timers on buffs and debuffs"] = true
	L["Aura Text Scale"] = true
		L["Controls the size of the aura font"] = true
	L["Player Auras"] = true
		L["Display auras on player frame"] = true
	L["Player Only My Debuffs"] = true
		L["Display only debuffs on your player frame (must have playerauras enabled)"] = true
	L["Target Auras"] = true
		L["Display auras on target frame"] = true
	L["Target Only My Debuffs"] = true
		L["Display only your debuffs on the target frame. (and anything displayed in the debuff whitelist)"] = true
	L["ToT Debuffs"] = true
		L["Display debuffs on target of target frame"] = true
	L["Focus Debuffs"] = true
		L["Display only your debuffs on the targets frame."] = true
	L["Boss Buffs"] = true
		L["Display buffs on boss frames"] = true
	L["Boss Debuffs"] = true
		L["Display debuffs on boss frames."] = true
	L["Arena Buffs"] = true
		L["Display buffs on arena frames."] = true
	L["Arena Debuffs"] = true
		L["Display debuffs on arena frames."] = true
	L["Filter Debuff Borders"] = true
		L["Toggles whether you want border of debuffs filtered."] = true
	L["Buff Rows"] = true
		L["Controls how many buffs are displayed.(player/target frames only)"] = true
	L["Debuff Rows"] = true
		L["Controls how many debuffs are displayed.(player/target frames only)"] = true
L["Other Stuff"] = true
	L["Class Bars"] = true
		L["Toggles whether you want to use class related bars.(ie: totem bar, rune bar, eclipse bar)"] = true
	L["Weakened Soul Bar"] = true
		L["Toggles whether you want to display a weakened soul bar"] = true
L["Raid/Party Settings"] = true
	L["Configure Settings for Raid and Parties."] = true
	L["Range Opacity"] = true
		L["Toggles whether you want to use alpha opacity for units out of range"] = true
	L["Alpha Amount"] = true
		L["Controls how much alpha is used when unit is out of range"] = true
	L["Show Self"] = true
		L["Toggles whether you want to be displayed in party frames"] = true
	L["Show Symbols"] = true
		L["Toggles whether you want to show raid symbols in frames"] = true
	L["Show Aggro"] = true
		L["Toggles whether you want to show aggro on all raid frames"] = true
	L["Show Debuffs"] = true
		L["Toggles whether you want to show aggro on all raid frames"] = true
	L["Healcomm"] = true
		L["Toggles whether you want to display incoming heals"] = true
	L["Display HP Vertically"] = true
		L["Toggles whether you want to display health vertically instead.(HEAL LAYOUT ONLY)"] = true
	L["Display HP Deficit"] = true
		L["Toggles whether you want to display HP deficits instead.(HEAL LAYOUT ONLY)"] = true
	L["Hide Power"] = true
		L["Toggles whether you want to hide Power from being displayed on raid/party frames.(DPS LAYOUT ONLY)"] = true
	L["Show Main Tank"] = true
		L["Toggles Main Tank display."] = true
	L["Show Main Assist"] = true
		L["Toggles Main Assist display."] = true
	L["Show Boss Frames"] = true
		L["Toggles whether you want to display frames for bosses."] = true
	L["Raid Buff Display Size"] = true
		L["Size of the buff icon on raidframes"] = true
	
-- Name plates
L["Nameplates"] = true
	L["NP_DESC"] = "Configure options for nameplates"
	L["Show Health"] = true
		L["Display health values on nameplates, this will also increase the size of the nameplate"] = true
	L["Color health by Threat"] = true
		L["Color the nameplate's healthbar by your current threat, Example: good threat color is used if your a tank when you have threat, opposite for DPS."] = true
	L["Toggle Combat"] = true
		L["Toggles the nameplates off when not in combat."] = true
	L["Track Debuffs"] = true
		L["Tracks your debuffs on nameplates."] = true
	L["Track CC"] = true
		L["Tracks CC debuffs on nameplates from you or a friendly player"] = true
L["Colors"] = true
	L["Good Color"] = true
		L["This is displayed when you have threat as a tank, if you don't have threat it is displayed as a DPS/Healer"] = true
	L["Bad Color"] = true
		L["This is displayed when you don't have threat as a tank, if you do have threat it is displayed as a DPS/Healer"] = true
	L["Transition Color"] = true
		L["This color is displayed when gaining/losing threat"] = true
		
--Actionbar
L["Action Bars"] = true
	L["AB_DESC"] = "Adjust settings for actionbars and cooldown text on action buttons"
	L["Hotkey Text"] = true
		L["Display hotkey text on action buttons"] = true
	L["Right Bar on Mouseover"] = true
		L["Hide the right action bar unless mouseovered"] = true
	L["Shape Shift Bar"] = true
		L["Hide the shape shift action bar"] = true
	L["Shape Shift on Mouseover"] = true
		L["Hide the shape shift action bar unless mouseovered"] = true
	L["Vertical Shape Shift"] = true
		L["Make the shape shift bar grow vertically instead of horizontally"] = true
	L["Display Grid"] = true
		L["Display grid backdrop behind empty buttons"] = true
	L["Pet Bar below main actionbar"] = true
		L["Positions the pet bar below the main actionbar instead of to the right side of the screen"] = true
	L["Button Size"] = true
	L["Button Spacing"] = true
	L["Pet Button Size"] = true
	L["Main actionbar on top"] = true
		L["Positions the main actionbar above all other actionbars"] = true
	L["Macro Text"] = true
	L["Micro Bar"] = true
		L["Display blizzards default microbar, this will disable the right click menu on minimap"] = true
	L["Micro Bar on Mouseover"] = true
		L["Display blizzards default microbar when mouseovered"] = true
	L["Cooldown Text"] = true
	L["Threshold"] = true
		L["Threshold before turning text red and displaying decimal places"] = true
	L["Expiring"] = true
		L["This gets displayed when your below the threshold"] = true
	L["Seconds"] = true
	L["Minutes"] = true
	L["Hours"] = true
	L["Days"] = true
	
-- Misc Settings


	
-- Chat Settings
L["Chat Options"] = true
	L["CHAT_DESC"] = "Allows you to customize settings for chat."
	L["Toggles whether you want to use tukui chat system."] = true
L["Whisper sound"] = true
	L["Toggles whether you want to play a sound when you receive whispers."] = true
L["Background"] = true
	L["Toggles whether you want to use backgrounds for chat windows."] = true
L["Fading"] = true
	L["Toggles whether you want to fade out chat text when not active."] = true
L["Justify Right"] = true
	L["Toggles whether you want to justify text to the right in your right char box window."] = true
L["Height"] = true
	L["Choose the height of chat windows."] = true
L["Width"] = true
	L["Choose the width of chat windows."] = true
L["Toggle Chat In Combat"] = true
	L["When you enter combat, the selected window will be hidden."] = true
	L["None"] = true
	L["Left"] = true
	L["Right"] = true
	L["Both"] = true
	
-- Tooltips
L["Tooltips"] = true
	L["TT_DESC"] = "Allows you to customize your settings for Tooltips."
	L["Toggles whether you want to use tukui tooltips."] = true
L["Hide In Combat"] = true
	L["Toggles whether you want to show tooltips while in combat."] = true
L["Hide Combat in Raid"] = true
	L["Hide tooltip when entering combat only inside a raid instance"] = true
L["Hide Actionbar Tooltips"] = true
	L["Toggles whether you want to hide tooltips from actionbar buttons."] = true
L["Hide Unitframe Tooltips"] = true
	L["Toggles whether you want to hide tooltips from unitframes."] = true
L["Cursor"] = true
	L["When enabled allows you to have tooltips display where your mouse is."] = true
L["Who Target"] = true
	L["When enabled allows you to see who is targetting you while in a raid or party."] = true
	

--Datatext
L["DT_POS"] = "\n\n0 - Disabled\n1 - LEFT PANEL, LEFT\n2 - LEFT PANEL, CENTER\n3 - LEFT PANEL, RIGHT\n4 - RIGHT PANEL, LEFT\n5 - RIGHT PANEL, CENTER\n6 - RIGHT PANEL, RIGHT\n7 - MIDDLE, OUTER LEFT\n8 - MIDDLE, LEFT\n9 - MIDDLE, CENTER\n10 - MIDDLE, RIGHT\n11 - MIDDLE, OUTER RIGHT"


-- Media group
L["Media"] = true
	L["MEDIA_DESC"] = "Customize display settings"
L["Fonts"] = true
L["General Font"] = true
	L["GFONT_DESC"] = "The font that the core of the UI will use"
L["UnitFrame Font"] = true
	L["UFFONT_DESC"] = "The font that unitframes will use"
L["Combat Font"] = true
	L["COMFONT_DESC"] = "The font that combat text will use. WARNING: This requires a game restart after changing this option."
L["Chat Font"] = true
	L["CHTFONT_DESC"] = "The font that chatframes will use"
L["Chat Font Size"] = true
	L["CHTSIZE_DESC"] = "Change the size of your chat font."
L["Datatext Font"] = true
	L["DTFONT_DESC"] = "The font that datatexts will use"
L["Datatext Font Size"] = true
	L["DTSIZE_DESC"] = "Change the size of your datatext font."
L["Textures"] = true
L["Default Texture"] = true
	L["DTEX_DESC"] = "Texture that gets used on just about everything"
L["Glow Border"] = true
	L["GTEX_DESC"] = "Shadow Effect"
L["Backdrop Texture"] = true
	L["BTEX_DESC"] = "Used on almost all frames"
L["Sounds"] = true
L["Whisper Sound"] = true
	L["WHISOUND_DESC"] = "Sound that is played when recieving a whisper"
L["Warning Sound"] = true
	L["WARSOUND_DESC"] = "Sound that is played when you don't have a buff active"
L["Colors"] = true
L["Border Color"] = true
	L["BCOLOR_DESC"] = "Main Frame's Border Color"
L["Backdrop Color"] = true
	L["BDROP_DESC"] = "Main Frame's Backdrop Color"
L["Backdrop Fade Color"] = true
	L["BDROPFADE_DESC"] = "Main Frame's that use Transparency."
L["Alt Border Color"] = true
	L["ABDROP_DESC"] = "Main Frame's Alternate Border Color"
	
-- Class timers
L["Class Timers"] = true
	L["CLASSTIMER_DESC"] = "Adjust settings for classtimers"
	L["Enable Class Timers"] = true
	L["Bar Height"] = true
		L["Controls the height of the bar"] = true
	L["Bar Spacing"] = true
		L["Controls the spacing in between bars"] = true
	L["Icon Position"] = true
		L["0 = Left\n1 = Right\n2 = Outside Left\n3 = Outside Right"] = true
	L["Layout"]	 = true
		L["LAYOUT_DESC"] = "1 - Player, Target, Proc auras in one frame right above player frame\n2 - Player and target auras separated into two frames above player frame\n3 - Player, target and trinket auras separated into three frames above player frame\n4 - Player and trinket auras are shown above player frame and target auras are shown above target frame\n 5 - Everything above player frame, no target debuffs."
	L["Spark"] = true
		L["Display spark"] = true
	L["Cast Seperator"] = true
	L["Buff"] = true
	L["Debuff"] = true
	L["Proc"] = true
	L["General Font"] = true
		L["Font used for classtimers."] = true
	L["General Font Size"] = true
		L["Size used for the General Font"] = true
	
	
	
	
-- Spellfilters
L["Select Spell"] = true
L["Enabled"] = true
L["Position"] = true
	L["POS_DESC"] = "Position where the buff appears on the frame"
L["Any Unit"] = true
	L["ANYUNIT_DESC"] = "Display the buff if cast by anyone?"
L["Color"] = true
L["Procs"] = true
L["Choose Filter"] = true
	L["CFILTER_DESC"] = "Choose the filter you want to modify."
L["Choose the filter you want to modify."] = true
L["New Spell ID"] = true
L["New name"] = true
		L["Add a new spell name / ID to the list."] = true
	L["Remove ID"] = true
	L["Remove Name"] = true
		L["Remove a name or ID from the list."] = true
	L["New ID"] = true
	L["Not valid spell id"] = true
L["You may only delete spells that you have added. Default spells can be disabled by unchecking the option"] = true
	L["Spell not found in list"] = true
L["Display the buff if cast by anyone?"] = true
L["Only display on this type of unit"] = true
L["Show Ticks"] = true
L["Unit Type"] = true
L["All"] = true
L["Friendly"] = true
L["Enemy"] = true
L["Fill only if you want to see line on bar that indicates if its safe to start casting spell and not clip the last tick, also note that this can be different from aura id."] = true
L["To disable set to zero, otherwise set to the amount of times the spell ticks in a cast"] = true

L["Filter whether or not a nameplate is shown by the name of the nameplate"] = true
	L["Filter the buffs that get displayed on arena units."] = true
	L["Set buffs that will never get displayed."] = true
	L["These debuffs will always get displayed on the Target Frame, Arena Frames, and Nameplates."] = true
	L["These debuffs only get displayed on the target unit when the unit happens to be an enemy player."] = true
	L["These debuffs will be displayed on your raid frames in addition to any debuff that is dispellable."] = true
	L["These buffs are displayed on the healer raid and party layouts"] = true
	L["These buffs are displayed on the DPS raid and party layouts"] = true
	L["These buffs are displayed on the pet frame"] = true
	L["These buffs are displayed no matter your class you must have a layout enabled that uses trinkets however for them to show"] = true
	L["These buffs/debuffs are displayed as a classtimer, where they get positioned is based on your layout option choice"] = true
	L["These spells when cast will display tick marks on the castbar"] = true
	L["Filter the error messages that are never displayed."] = true